# You need the AZURE_WEB_APP_NAME and to download the deployment profile and
# add it as a secret to this repo with the name AZURE_WEBAPP_PUBLISH_PROFILE
name: Trigger auto deployment for demo-container

#env:
  # !!!! UPDATE THESE VARIABLE BELOW !!!!
  #AZURE_WEBAPP_NAME: changeme 
  #AZURE_GROUP_NAME: changeme

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo. Remove comments to enable
  #push:
  #  branches:
  #    [ main ]

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #Used some syntax help from ChatGPT to assist with setting up Docker secrets etc.
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push container image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
          file: ./Dockerfile

  
